### PR TITLE
Added protection when top number is less than number of genes.

### PR DESCRIPTION
**Pull request by LTLA**
Pretty much as the title says, really. Picked it up in one of the `scran` tests.

### CODE REVIEW

**Comment by davismcc** [comment]
Thanks, Aaron!

**Comment by LTLA** [comment]
When you get the chance, can you push this through to BioC-devel if you haven't done so already?

**Comment by davismcc** [comment]
Aye. Will do this afternoon. 
I'm working again on the scater manuscript. Given your contributions to the package I'd like to make you an author - would you be happy with that? The price - on top of time served - would be a small commitment to reviewing the ms, (I hope) shortly. 
BestDavis 

Sent from mobile

On Wed, Jul 13, 2016 at 2:34 PM +0100, "Aaron Lun" notifications@github.com wrote:

When you get the chance, can you push this through to BioC-devel if you haven't done so already?

**Comment by LTLA** [comment]
Might as well. You read mine and I'll read yours.

**Comment by davismcc** [comment]
Cool. This is done now - latest version committed to BioC-devel.

**Pull request merged**
